# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r


language: R
cache: packages
warnings_are_errors: false
repos:
  CRAN: https://packagemanager.rstudio.com/all/__linux__/xenial/latest
